global using CodeBase.Models.ConfigModels;
global using CodeBase.Models.ViewModels;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using CodeBase.Models.ErrorModel;
global using CodeBase.Models.DTOModels.OrderDTOS;
global using Microsoft.Extensions.Caching.Memory;